export const EMAIL_INPUT_CHANGED = 'EMAIL_INPUT_CHANGED';
export const SSN_INPUT_CHANGED = 'SSN_INPUT_CHANGED';
export const PHONE_INPUT_CHANGED = 'PHONE_INPUT_CHANGED';
export const COUNTRY_INPUT_CHANGED = 'COUNTRY_INPUT_CHANGED';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
// Error messages 
export const INVALID_EMAIL = 'INVALID_EMAIL';
export const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
export const INVALID_SSN = 'INVALID_SSN';
export const INVALID_COUNTRY_SELECTION = 'INVALID_COUNTRY_SELECTION';
